[project]
name = "mophones"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dbt>=1.0.0.40.14",
    "dbt-core>=1.10.18",
    "dbt-databricks>=1.11.0",
]
